name: Build Everything TGW

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag of llama-cpp-binaries to build: v0.1.0'
        default: 'v0.1.0'
        required: true
        type: string

permissions:
  contents: write

jobs:          
  build_textgen_wheels_windows:
    name: CUDA Wheels Windows
    uses: ./.github/workflows/build-wheels-cuda.yml
    with:
      version: ${{ inputs.version }}
      config: 'os:windows-2019'

  build_textgen_wheels_linux:
    name: CUDA Wheels Linux
    uses: ./.github/workflows/build-wheels-cuda.yml
    with:
      version: ${{ inputs.version }}
      config: 'os:ubuntu-22.04'

  build_wheels_cpu:
    name: CPU-only Wheels
    uses: ./.github/workflows/build-wheels-cpu.yml
    with:
      version: ${{ inputs.version }}
      
  build_wheels_macos:
    name: MacOS Metal Wheels
    uses: ./.github/workflows/build-wheels-macos.yml
    with:
      version: ${{ inputs.version }}
      
  build_wheels_rocm:
    name: ROCm Wheels
    uses: ./.github/workflows/build-wheels-rocm.yml
    with:
      version: ${{ inputs.version }}
